# Homework 02 - Python Daniel Teeuwsen

In this homework, we will be working with Python arrays.

Use the NumPy documentation for your installed version of NumPy to do the following excercises. The specific `numpy` commands to use are in paratheses after the excercise instructions. 

In [169]:
# I AM INCLUDING THIS HERE THIS TIME, SO THAT NEXT TIME, YOU WON'T FORGET IT!
import numpy as np

#### Excercise 1

Create a 1D NumPy array of integer numbers from 0 to 9 ([`numpy.arange`][arange]), and printit out all at once with :
```python
print(my_array)
```

[arange]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

In [170]:
my_array=np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


#### Excercise 2

Write a `for` loop and print the first 5 values **only** of the array of the previous problem, one at a time.

**A.** In the first `for` loop, use an integer iterator and the `range` function. Access the elements of your array using the iterator as an *index* to the array elements, like this:
```python
for i in range(?):
  print(my_array[i])
```

**B.** In the second `for` loop, use the array *itself* as the iterator. 

In [171]:
for i in range(5):
    print(my_array[i])

0
1
2
3
4


In [172]:
for i in my_array[0:5:1]:
    print(my_array[i])

0
1
2
3
4


#### Excercise 3
Create a three row, five colulmn matrix of all 7's ([`numpy.repeat`][repeat], [`numpy.reshape`][reshape]). 

**A.** Print the whole matrix.

**B.** Print the second column only.

[repeat]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html
[reshape]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

In [173]:
threeByFiveMatrixOfSevens=np.repeat(7,15).reshape(3,5)
print(threeByFiveMatrixOfSevens)  #A

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [174]:
threeByFiveMatrixOfSevens[:,1]   #B

array([7, 7, 7])

#### Excercise 4
Extract and `print` all odd numbers from the following array: 
```python
arr = numpy.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13])
```

Do this with three different methods. 

**A.** First with a `for` loop and `list.append`, for example: 
```python
new_list = []
for i in old_list:
    if expression(i):
        new_list.append(old_list[i])
```
where you substitute `expression` with the test for oddness of that individual element. Finally, convert the list to a NumPy array before printing it.
    
**B.** Second, do it by *list comprehensions*, for example:
```python
new_list = [old_list[i] for i in old_list if expression(i)]
```
In this case, use NumPy arrays and not python lists the whole time.

**C.** Third, simplify the list comprehension, for example: 

```python
new_list = old_list[expression(i)]
```
 Again, use numpy arrays and not python lists the whole time.

Make certain that your the varaible you `print` to see the output is a NumPy array.

In [175]:
##Part A

old_list=np.arange(14) #technically an array not a list
new_list=[]            #actually a list
for i in old_list:
    if i%2==1:
        new_list.append(old_list[i])
new_list=np.array(new_list)
print(new_list)

[ 1  3  5  7  9 11 13]


In [176]:
##Part B

old_listB=np.arange(14)
new_listB=np.array([old_listB[i] for i in old_listB if old_listB[i]%2==1])
print(new_listB)

[ 1  3  5  7  9 11 13]


In [177]:
##Part C

old_listC=np.arange(14)
new_listC=old_listC[old_listC%2==1]
print(new_listC)

[ 1  3  5  7  9 11 13]


#### Excercise 5
Replace the odd numbers form the above array of numbers with a value of -1 ([`numpy.where`](where)). 

[where]:https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [178]:
##Exercise 5 Solution

myList=np.arange(14)
np.where(myList%2==1,-1,myList) #Alternatively np.where(myList%2==0,myList,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1])

#### Excercise 6

**A.** Create an equally spaced NumPy array of data points, from *exactly* $x=0$ to *exactly* $x=100$, using *about* 1000 data points. ([`numpy.linspace`][linspace]) **Also** save the step size in a seperate variable.

How many data points should you chose to get a nice decimal number of 0.1 as the step size?

Print the *last* 5 data points, and the step size.

**B.** Without creating any new arrays, recale the data values in the array of the previous problem by a factor of 5.

**C.**  Use NumPy functions to find the average and standard deviation of the data in your array from the previous problem.

[linspace]: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

In [186]:
newArray,step=np.linspace(0,100,num=1000,retstep=True)    #Part A
print(newArray)
print("\n array size = " + str(newArray.size) )
stepSize=newArray[1]
print("\n step size = " + str(step))

print("\n The last 5 data points in the array are: \n")
for i in range(5):
    print(" " + str(newArray[newArray.size-(5-i)]))
    
#1001 data points should be chosen to get a step size of 0.1 as already explained in the below cell

[  0.           0.1001001    0.2002002    0.3003003    0.4004004
   0.5005005    0.6006006    0.7007007    0.8008008    0.9009009
   1.001001     1.1011011    1.2012012    1.3013013    1.4014014
   1.5015015    1.6016016    1.7017017    1.8018018    1.9019019
   2.002002     2.1021021    2.2022022    2.3023023    2.4024024
   2.5025025    2.6026026    2.7027027    2.8028028    2.9029029
   3.003003     3.1031031    3.2032032    3.3033033    3.4034034
   3.5035035    3.6036036    3.7037037    3.8038038    3.9039039
   4.004004     4.1041041    4.2042042    4.3043043    4.4044044
   4.5045045    4.6046046    4.7047047    4.8048048    4.9049049
   5.00500501   5.10510511   5.20520521   5.30530531   5.40540541
   5.50550551   5.60560561   5.70570571   5.80580581   5.90590591
   6.00600601   6.10610611   6.20620621   6.30630631   6.40640641
   6.50650651   6.60660661   6.70670671   6.80680681   6.90690691
   7.00700701   7.10710711   7.20720721   7.30730731   7.40740741
   7.50750751   7.60

`numpy.linspace` normally doesn't return the `stop` value as part of the array unless `endpoint=True`. To get a nice step size of 0.1, we would need 1001 data points.

In [187]:
newArray=newArray*5   #Part B
print(newArray)       

                      #Note that you should be careful not to run the code multiple times without resetting the original array
                      #Each time the code is run the values will change 0.1 to 0.5 to 2.5 etc. You can avoid this by running
                      #the previous cell each time you wish to rerun this cell.

[  0.           0.5005005    1.001001     1.5015015    2.002002
   2.5025025    3.003003     3.5035035    4.004004     4.5045045
   5.00500501   5.50550551   6.00600601   6.50650651   7.00700701
   7.50750751   8.00800801   8.50850851   9.00900901   9.50950951
  10.01001001  10.51051051  11.01101101  11.51151151  12.01201201
  12.51251251  13.01301301  13.51351351  14.01401401  14.51451451
  15.01501502  15.51551552  16.01601602  16.51651652  17.01701702
  17.51751752  18.01801802  18.51851852  19.01901902  19.51951952
  20.02002002  20.52052052  21.02102102  21.52152152  22.02202202
  22.52252252  23.02302302  23.52352352  24.02402402  24.52452452
  25.02502503  25.52552553  26.02602603  26.52652653  27.02702703
  27.52752753  28.02802803  28.52852853  29.02902903  29.52952953
  30.03003003  30.53053053  31.03103103  31.53153153  32.03203203
  32.53253253  33.03303303  33.53353353  34.03403403  34.53453453
  35.03503504  35.53553554  36.03603604  36.53653654  37.03703704
  37.53753754

In [188]:
np.mean(newArray)   #Part C

250.00000000000003

In [189]:
np.std(newArray)    #Part C 

144.48197710571046

Note that the mean and standard deviation computed are those of the array multiplied by 5. The mean and standard deviation of the original data would simply be 250/5=50 and 144.5/5 respectively. 